# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

one_pois_slice <- function(L, k, mean, precision) {
    .Call('_gibbs_utils_one_pois_slice', PACKAGE = 'gibbs.utils', L, k, mean, precision)
}

slice_sample_pois <- function(L, k, mean, precision) {
    .Call('_gibbs_utils_slice_sample_pois', PACKAGE = 'gibbs.utils', L, k, mean, precision)
}

one_pois_slice_mv <- function(L, k, mean, Q, i) {
    .Call('_gibbs_utils_one_pois_slice_mv', PACKAGE = 'gibbs.utils', L, k, mean, Q, i)
}

slice_sample_pois_mv <- function(L, k, mean, Q) {
    .Call('_gibbs_utils_slice_sample_pois_mv', PACKAGE = 'gibbs.utils', L, k, mean, Q)
}

